### ISSUE TITLE
backing up private repos on org with different user.

### ISSUE THREAD

**Issue by edux** [josegonzalez/python-github-backup#102]
Hi, I am trying to backup an org that has public and private repos. I am using a service account with a token with privileges on public and private repos, but this line:

https://github.com/josegonzalez/python-github-backup/blob/f8be34562b51a16d97c64ba69a4791c7897fbc3a/bin/github-backup#L527

prevents the backup to run because org != user, a quick test commenting that line got it working but I'd like to understand the purpose of that check or if it will have some unwanted side effect.

**Comment by whwright** [comment]
Is this the same issue discussed in #98?

**Comment by edux** [comment]
Yes, my bad I didn't saw it. Closing as duplicates #98
