### ISSUE TITLE
Add topic: github-backup

### ISSUE THREAD

**Issue by katrinleinweber** [josegonzalez/python-github-backup#111]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/github-backup](https://github.com/topics/github-backup), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by josegonzalez** [comment]
Added, thanks!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for adding :-)
