### ISSUE TITLE
github-backup is not backing up the "releases" (and its information and "assets")

### ISSUE THREAD

**Issue by coldcoff** [josegonzalez/python-github-backup#116]
Thank you for that wonderful tool. Installed, configured, worked :-)

One thing I'm missing, though:
It seems it is not backing up the releases pages. There can be quite some valuable information on those pages, see for example:
https://github.com/go-gitea/gitea/releases
Especially loosing the "Assets" is probably hurting.

Can support for these "releases" be added?

Thank you!

**Comment by coldcoff** [comment]
https://help.github.com/en/articles/about-releases

**Comment by timm3** [comment]
@coldcoff Out of curiosity, by "assets" do you mean the "manually" attached ones, or those that github attaches by default (zip+tarball) ?

**Comment by coldcoff** [comment]
@josegonzalez: Thanks, hmmmm ... let me see if I will create a pull request. Probably I just hack a small script around the interesting repos with https://github.com/PyGithub/PyGithub or bash/curl/jq.
OTOH: How long do you estimate for you to build that functionality? Fully integrated in your project?

@timm3: the manually attached ones, especially the description and the binary uploads that one can attach to a release. The github attached ones (zip + tarball) would be redundant.

**Comment by josegonzalez** [comment]
~2 hour.

**Comment by timm3** [comment]
I've been working on this and am puzzled as to why github responds to requests to download the assets with http(400) _and_ a redirect url that's a signed aws-s3 download.

**Comment by coldcoff** [comment]
@josegonzalez: It Seems #117 adresses my Issue. Can #117 be merged? Then #117 and #116 cqan be closed altogether.

@timm3 and @whwright: Thank you!

**Comment by josegonzalez** [comment]
Released in 0.24.0.
