### ISSUE TITLE
Feature Request: Milestone and Label backup

### ISSUE THREAD

**Issue by aensley** [josegonzalez/python-github-backup#12]
Thank you for this tool. It is working great for me to backup repositories, wikis, and issues. Two things I noticed missing that prevent it from being a *complete* backup are lists of milestones and labels for a repository. I know this information is essentially contained within the issues, but it would be useful to have them in their own separate lists, especially to retain labels/milestones without associated issues.

The GitHub API has simple endpoints for each:

 * [Milestones](https://developer.github.com/v3/issues/milestones/) - `GET /repos/:owner/:repo/milestones?state=all`
 * [Labels](https://developer.github.com/v3/issues/labels/) - `GET /repos/:owner/:repo/labels`

Thanks for your consideration!

**Comment by josegonzalez** [comment]
Pull requests accepted! :)

**Comment by aensley** [comment]
This one, I think I could do. I'll try to work on it soon.

**Comment by aensley** [comment]
Since PR #14 was accepted, I'll mark this closed. Thanks!

**Comment by aensley** [comment]
I'm not very familiar with how `python-pip` works or where it pulls code from, but running `pip install github-backup` still pulls in an older version than when PR #14 was merged. Is there any way to update that version with the current GH master code?

**Comment by josegonzalez** [comment]
Looks like I'll need to make a new release on pypi in the morning.
