### ISSUE TITLE
OSError: [Errno 2] No such file or directory on Ubuntu 18.04

### ISSUE THREAD

**Issue by AlienKevin** [josegonzalez/python-github-backup#122]
Hi, I encountered `OSError: [Errno 2] No such file or directory on Ubuntu 18.04` when trying to backup my github using `github-backup AlienKevin --token *************** --all`. Can someone help please?
![Capture](https://user-images.githubusercontent.com/22850071/60984804-28647100-a2f1-11e9-9f06-8f835f423d3c.PNG)

Environment:
Ubuntu 18.04 in VirtualBox on Windows 10 host

**Comment by josegonzalez** [comment]
Do you have the `git` binary available?

**Comment by AlienKevin** [comment]
@josegonzalez Sorry for the late reply, I installed `git` and everything worked. Thanks for this amazing project!
