### ISSUE TITLE
Can't Use As GitHub App

### ISSUE THREAD

**Issue by timm3** [josegonzalez/python-github-backup#123]
Currently, one cannot use this library and authenticate as a [github application](https://developer.github.com/apps/about-apps/).

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by timm3** [comment]
I'm prepping it, but it builds on the PR for #50.

**Comment by dmwyatt** [comment]
@timm3 Did you manage to get a PR together?

**Comment by timm3** [comment]
I didn't see that josegonzalez commented on #50 with additional requirements for the PR to be accepted, and continued work on the fork. Maybe some time later?

**Comment by timm3** [comment]
PR #121 was closed (by me), but I've opened another one as #145.
Once it gets some attention and merged in, I should be able to get this issue seen to rather quickly.

**Comment by timm3** [comment]
@josegonzalez this can now be closed, as PR 146 was merged :+1:
