### ISSUE TITLE
Assets can be overwritten

### ISSUE THREAD

**Issue by whwright** [josegonzalez/python-github-backup#126]
While looking at #125 I noticed that assets are all downloaded to `repositories/${repo_name}/releases/${asset}`. Therefore, if multiple releases have the same asset name, the last one will win and overwrite the rest. These should probably be separated into another directory by version name.

This might get a little weird, as it's possible for assets to have invalid path parameters such as `/`. 

I'll fix this when I find the time.

**Comment by einsteinx2** [comment]
Yep I'm seeing this as well. I think the solution would be to download to `repositories/${repo_name}/releases/${version}/${asset}` where for example if repo name is `somerepo`, the release json file is named `1.0.json`, and the asset name is `build.exe` it would download to `repositories/somerepo/releases/1.0/build.exe`.

Also, I noticed that right now if an asset has already been downloaded, on all subsequent syncs (I'm using `--incremental` but maybe this applies either way?) then it should skip downloading the file if it already exists on disk. Not sure the best way to check for that, I need to look into the code, but that would vastly improve sync time for lots of repos (in my case I have over 500 starred repos, some of which have many releases).

I'm currently working on a PR to fix handling 404 responses and other download errors crashing the script, but after that I'll implement this and open a PR.
