### ISSUE TITLE
Feature Request: Restore

### ISSUE THREAD

**Issue by aensley** [josegonzalez/python-github-backup#13]
The backup works well, but in order to be a valid backup, there has to be some way to restore all that information back to GitHub. I know this is a monolithic request, possibly more than doubling the work put into the project so far. Just thought I'd put this out there since I didn't see any past issues about it.

**Comment by jonasrmichel** [comment]
I second @aensley's request. This is an amazing tool and a `restore` feature would be awesome.

**Comment by josegonzalez** [comment]
Pull requests welcome!

To be honest, this already does exactly all I need. If at any point in time my company needs to restore a repository, then maybe I'd be willing to look at it, but for now I don't have any plans to complete this task.

**Comment by mjonker-embed** [comment]
+1

**Comment by srault95** [comment]
+1

**Comment by josegonzalez** [comment]
+2

Still doesn't mean I'm going to work on this. If someone wants to give it a go, by all means!

**Comment by josegonzalez** [comment]
Going to close this. No one stepped up to work on the feature, sponsor me to do it, and it's not in the scope of what the original project was meant to be.

If anyone would like to contribute a pull request or monetarily contribute to me creating such functionality, feel free to do so.
