### ISSUE TITLE
Bash gives not a valid identifier error

### ISSUE THREAD

**Issue by orhanarifoglu** [josegonzalez/python-github-backup#139]
Hi , just installed this but whenever I try to run it like 

export ACCESS_TOKEN=mytoken github-backup orhanarifoglu --token $ACCESS_TOKEN --organization --output-directory /home/pi --repositories

I get errors like
-bash: export: `--token': not a valid identifier
-bash: export: `SOME-GITHUB-TOKEN': not a valid identifier
-bash: export: `--organization': not a valid identifier
-bash: export: `--output-directory': not a valid identifier

Anyone know why? Thanks.

**Comment by einsteinx2** [comment]
You need to separate the access token export and the command into two commands like this:

```
export ACCESS_TOKEN=mytoken
github-backup orhanarifoglu --token $ACCESS_TOKEN --organization --output-directory /home/pi --repositories
```

Alternatively, removing the export command should also work (when you set environment variables inline with a command you don't use export, right now bash things everything after `export ACCESS_TOKEN=` is what you're exporting):

`ACCESS_TOKEN=mytoken github-backup orhanarifoglu --token $ACCESS_TOKEN --organization --output-directory /home/pi --repositories`

**Comment by josegonzalez** [comment]
Closing as the above answers the question.

**Comment by orhanarifoglu** [comment]
Thanks
