### ISSUE TITLE
Latest release listed as 0.10.1

### ISSUE THREAD

**Issue by rlbdv** [josegonzalez/python-github-backup#169]
Not sure if it's intentional, but https://github.com/josegonzalez/python-github-backup lists 0.10.1 as the latest release.

**Comment by josegonzalez** [comment]
I'm too lazy to update the release script to turn the tag into a github release, so I deleted all the releases. The code is still there, just as normal git tags.

**Comment by rlbdv** [comment]
Jose Diaz-Gonzalez <notifications@github.com> writes:

> I'm too lazy to update the release script to turn the tag into a
> github release, so I deleted all the releases. The code is still
> there, just as normal git tags.

Ahh, right -- I think that's pretty common, and preferable to having the
"pinned" stale release on the main page.  Thanks.
