### ISSUE TITLE
Backup sometimes hangs

### ISSUE THREAD

**Issue by mjonker-embed** [josegonzalez/python-github-backup#18]
We are running the backup as a cron job on hourly basis. I've notived that the proces hangs sometimes.

Command: `/usr/local/bin/github-backup -O -P -F --all --prefer-ssh -t <token> -o /home/info/github-backup <repo> > /dev/null`

Attaching strace to the proces shows nothing:
```
sudo strace -p 19794 
Process 19794 attached - interrupt to quit
read(4,
```
It doesn't show any further progress.

Do you need other information from the process? The process is still hanging on my server.

**Comment by josegonzalez** [comment]
All it does it call subprocess, so what other processes are running under it?

**Comment by mjonker-embed** [comment]
There appears to be no subproces

```
root      1781  0.0  0.0  79072   404 ?        Ss   Jun02   0:06 cron
root     19792  0.0  0.0  98044     0 ?        S    Jun11   0:00  \_ CRON
info     19793  0.0  0.0   4408     4 ?        Ss   Jun11   0:00      \_ /bin/sh -c /usr/local/bin/github-backup -O -P -F --all --prefer-ssh -t <token> -o /home/info/github-backup <repo> > /dev/null
info     19794  0.0  0.0  42868     4 ?        S    Jun11   0:00          \_ python /usr/local/bin/github-backup -O -P -F --all --prefer-ssh -t <token> -o /home/info/github-backup <repo> > /dev/null
```

**Comment by josegonzalez** [comment]
Not sure what the problem is, it's probably waiting until it can make github requests because of rate limiting?

**Comment by mjonker-embed** [comment]
I don't have a hanging cron job now either.
