### ISSUE TITLE
Procedures for Restore

### ISSUE THREAD

**Issue by ryan-omni3** [josegonzalez/python-github-backup#185]
Great work.  Really like the tool.  

Any guidance on how to do a restore would be greatly appreciated.

For the repositories it seems like it would be
  git push --all origin

But for labels, pulls, issues, milestores, i'm not so sure.  Maybe someone has already addressed this in a fork?

**Comment by josegonzalez** [comment]
The project's name is `github-backup`. Restoring a backup is out of scope, and not something I'll be taking MRs for. Feel free to start your own project that does such a thing (I'll be happy to link out).
