### ISSUE TITLE
Exclude specific repositories from backup

### ISSUE THREAD

**Issue by NPounder** [josegonzalez/python-github-backup#203]
Add an option to exclude named repositories from the backup, e.g.:
`--exclude [REPOSITORY [REPOSITORY ...]]`

My use case is the same as in issue #135, I have one repository with many GB of release assests that I do not wish to back up each time. My work around is to backup everything except that repository, then separately backup that repository exluding release assets.

This is more general than @einsteinx2 suggested solution in #135 and requires multiple runs of github-backup, but it can be used to exclude anything from backup so may be useful for other use cases too.

I will submit a pull request.

**Comment by civcode** [comment]
I would love to see this feature in a future release.
