### ISSUE TITLE
Feature: offer docs how to run in docker

### ISSUE THREAD

**Issue by EugenMayer** [josegonzalez/python-github-backup#211]
Thank you for the great tool! We `dockerized` the pyhon lib to reduce the host system requirements and also isolate the run to a non privileged user to ensure everything is encapsulated if something goes wrong. See https://github.com/KontextWork/docker-github-backup

Should be as easy as

```
docker run --rm ghcr.io/kontextwork/github-backup --help
# or
docker run --rm ghcr.io/kontextwork/github-backup josegonzalez --repositories -t $TOKEN
```

See https://github.com/KontextWork/docker-github-backup for more

If there is and interest i would make an PR to update the docs

**Comment by ZhymabekRoman** [comment]
There is another Docker implementation: https://github.com/umputun/github-backup-docker

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by EugenMayer** [comment]
@ZhymabekRoman sorry - i assume i might be biased so i try to be extra objective:
The linked docker image does run under root. Considering we are dealing with a sensible operation like backup, on a backup server, running it as root in a container can have serious issues if anything goes rough. This is why i used a non root setup

@josegonzalez happy to do so, just since we have 2 candidates here, you have pick on for the PR i guess. As we see, it is needed, or we end up having more of the duplicate "dockerized" repos :) Let me know

**Comment by josegonzalez** [comment]
I'd rather the Dockerfile exist in this repository, and doesn't run as a daemon/cron. Folks can use their scheduler to do such a thing if they want vs running a persistent cron daemon in the image.
