### ISSUE TITLE
Pull requests are stored twice

### ISSUE THREAD

**Issue by eht16** [josegonzalez/python-github-backup#23]
Since pull requests are also issues in Github, currently pull requests are downloaded twice, as issue and as pull request.
When retrieved as issue, there are some information missing from the API, if I checked correctly. But you can differentiate issues from pull requests in the API response by the key `pull_request` according to the docs at https://developer.github.com/v3/issues/.

I wonder if it makes sense to drop all issues from the response which have the `pull_request` key set. At least if retrieving pull requests separately is requested by the user.

If accepted, I could make PR.

**Comment by josegonzalez** [comment]
That sounds reasonable to me.

**Comment by josegonzalez** [comment]
@eht16 mind making a pr?

**Comment by eht16** [comment]
Nope, will do. But it will take some time due to other priorities right now.

**Comment by josegonzalez** [comment]
:+1:

**Comment by eht16** [comment]
Here we go: #35 
Was actually easier than expected :).
