### ISSUE TITLE
Backup "watched" repositories

### ISSUE THREAD

**Issue by rom1504** [josegonzalez/python-github-backup#26]
I thought the `--watched             include watched repositories in backup` option would back up the watched repositories, but it actually only backup a list of watched repositories.

On github you often contribute to repository that are not in your own namespace and then watch them.
It would be useful to be able to backup all these repositories (as a new option for example)

**Comment by rom1504** [comment]
I think this would mostly consist in adding a --get-watched-repos there https://github.com/josegonzalez/python-github-backup/blob/master/bin/github-backup#L378 using the data from https://github.com/josegonzalez/python-github-backup/blob/master/bin/github-backup#L647
I might try it since the code is really easy to understand.

(an other option is using an external tool to read the watched.json and call github-backup with all the repos from there)

**Comment by josegonzalez** [comment]
@rom1504 mind making a PR?

**Comment by josegonzalez** [comment]
Going to close this. No one stepped up to work on the feature, sponsor me to do it, and I don't have any desire to personally implement it at this time.

If anyone would like to contribute a pull request or monetarily contribute to me creating such functionality, feel free to do so.
