### ISSUE TITLE
Error: "Skipping repo since it's not initialized" using Docker

### ISSUE THREAD

**Issue by paranerd** [josegonzalez/python-github-backup#260]
I'm trying to run the dockerized version but fail to do so because of the following error:

```
Skipping 2048 (https://*****:x-oauth-basic@github.com/paranerd/2048.git) since it's not initialized
```

Here's my `docker run` command:

```
sudo docker run -v ./data:/data ghcr.io/josegonzalez/python-github-backup -o /data --repositories -t {token} paranerd
```

Here's what I found out so far:

- The error only occurs when pulling from ghcr, building locally works just fine!
- I found that the issue seems to be originating by the fact that `git ls-remote` returns `128`, so I ran:
    ```
    sudo docker run --rm -e GIT_CURL_VERBOSE=1 -e GIT_TRACE=1 --entrypoint "/usr/bin/git" ghcr.io/josegonzalez/python-github-backup ls-remote https://github.com/paranerd/2048.git
    ```
    and
    ```
    sudo docker run --rm -e GIT_CURL_VERBOSE=1 -e GIT_TRACE=1 --entrypoint "/usr/bin/git" alpine/git ls-remote https://github.com/paranerd/2048.git
    ```
- The second command (using `alpine/git`) worked as expected
- The only difference between the two runs seems to be that the first (official) one sends an `Authorization` header which the second one (as well as my local one) does not and I have no idea where that's coming from...

Any suggestions to what may cause this are highly appreciated!

**Comment by paranerd** [comment]
Update:

Calling `git config -l` from within the official container shows

```
http.https://github.com/.extraheader=AUTHORIZATION: basic <base64-encoded-ghs-token>
```

This seems to be the root cause. However, I have no idea what put it there...

**Comment by paranerd** [comment]
I can confirm that calling

```
git ls-remote -c "http.https://github.com/.extraheader=AUTHORIZATION: basic <token>" ...
```

fixes the issue by manually adding my own token to the call.

It remains the question why this extra auth header exists in the first place.

**Comment by paranerd** [comment]
FWIW I found a workaround:

Using `docker run`

```bash
sudo docker build -t github-backup https://github.com/josegonzalez/python-github-backup.git#0.45.0 && sudo docker run -v /path/to/data:/data --name github-backup github-backup -o /data --repositories -t <token> <user>
```

or `docker compose`

```yaml
services:
  backup:
    build: https://github.com/josegonzalez/python-github-backup.git#0.45.0
    container_name: github-backup
    command: -o /data --repositories -t <token> <user>
    volumes:
      - ./data:/data
    restart: unless-stopped
```

Would be nice to have this fixed, though. Should be possible, according to the link above, by setting `persist-credentials` to `false`

**Comment by josegonzalez** [comment]
Pull requests welcome.
