### ISSUE TITLE
Don't stop everything if hooks are not available

### ISSUE THREAD

**Issue by rom1504** [josegonzalez/python-github-backup#27]
When you don't have admin access to the repo (for example if you only have contributor access), you don't have the right to see hooks.
Currently that means getting a
```
Retrieving <user> hooks
API request returned HTTP 404: Not Found
```
and then the program exits

It should indeed display a warning, but it shouldn't stop there. (you might have the rights to get the hooks in some repo and not others)

**Comment by rom1504** [comment]
something to do with https://github.com/eht16/python-github-backup/commit/534145d17892e914e68699f0bac9823aa3a7065f

**Comment by josegonzalez** [comment]
Mind adding a PR for this?

**Comment by josegonzalez** [comment]
@rom1504 friendly *bump* :)

**Comment by ribsadmin** [comment]
Excuse me for the grave-digging, but i seem to have run into this issue once more. (year 2021), as you expect, i starred the token a little:

` github-backup UMCU-RIBS --organization  -o '/var/backups/github-backup-RIBS'  --token 'ghp_************' --lfs --all --repositories`

fails on the first 404 found, the hooks page again:

`2021-05-28T14:39:17.967: Retrieving UMCU-RIBS hooks
2021-05-28T14:39:17.967: Requesting https://api.github.com/repos/UMCU-RIBS/ALICE/hooks?per_page=100&page=1
2021-05-28T14:39:18.122: API request returned HTTP 404: Not Found`

Here the script stops. Not using --all would continue to retrieve all other repositories.
