### ISSUE TITLE
Possible silent data loss with Git < 1.9.0 on git fetch

### ISSUE THREAD

**Issue by saj** [josegonzalez/python-github-backup#37]
Hello,

python-github-backup [invokes][fetch-line] `git fetch` with the `--tags` option. The meaning of the `--tags` option [changed][changelog] in Git 1.9.0:

> The meanings of the "--tags" option to "git fetch" has changed; the command fetches tags _in addition to_ what is fetched by the same command line without the option.

What you have now should produce expected results on later Git releases, but any of your users with earlier Git releases may unknowingly be relying upon incomplete backups.

On these earlier Git releases, `git fetch --tags` will only fetch objects reachable from tag refs, not branch refs.  In a repo with no tags, this means that *nothing* will be fetched.  This is particularly dangerous because the backup will look hunky dory at the time the user first experiments with python-github-backup (the initial `git clone` will fetch everything) and because no errors will be reported from then on.  (To be sure, this is not an erroneous condition from Git's perspective, hence, no errors.)

This is easy enough to fix for future users.  Some options I can think of:
- Stick a prominent caveat in your `README` with a suggested Git version requirement.
- Modify python-github-backup to parse a version string from `git --version` and bail out with a conspicuous failure message if it is earlier than 1.9.0.  (The *better safe than sorry* approach.)
- Replace the `--tags` option with something that will work on most Git releases still in production circulation today.  Perhaps an explicit set of refspecs.

Warning existing users of this problem may prove more difficult.

I am unsure which Git releases are distributed with Debian-derived LTS operating systems, but I do know that RHEL 7-derived operating systems ship with Git 1.8.  Anyone running an enterprise distro is likely to get burnt here.

[fetch-line]: https://github.com/josegonzalez/python-github-backup/blob/b6b6605acdd9576b02fc8745b49331287848ebf4/bin/github-backup#L672
[changelog]: https://github.com/git/git/blob/c2c5f6b1e479f2c38e0e01345350620944e3527f/Documentation/RelNotes/1.9.0.txt#L18

**Comment by josegonzalez** [comment]
Pull requests welcome.
