### ISSUE TITLE
Unable to restore issues and wiki 

### ISSUE THREAD

**Issue by ashay-maheshwari** [josegonzalez/python-github-backup#38]
I took a backup of one of my repository which container source files, issues and wiki.
I used github-backup to backup my repository. I restored the same repository by pushing the backup 
repository to origin master. I got my source files, but not issues and wiki.

Can anyone help me with this ?

**Comment by josegonzalez** [comment]
You can just push the wiki back up, but this project does not do any restoration of anything, just backup.

You will need to write your own code to handle restoration.
