### ISSUE TITLE
only 3 out of 80+ repos pulled down on an org

### ISSUE THREAD

**Issue by mikebz** [josegonzalez/python-github-backup#39]
github-backup -u mikebz -p **** --all -O tempoautomation

the organization has about 80 repos.  I ran the script with --all and -P and it only pulled a few down.  Not sure what the issue is, but it doesn't seem to want to traverse the full set of repos.

Is there a trick to get this script to work?

**Comment by josegonzalez** [comment]
Are they private repos? If so, you need to add the flag for that.

**Comment by mikebz** [comment]
--all --P --O was the magic combination.  Thank you!  I assumed that --all would grab everything.

**Comment by mikebz** [comment]
given the work around I am going to close the issue.
