### ISSUE TITLE
Refactor to be more easily importable

### ISSUE THREAD

**Issue by albertyw** [josegonzalez/python-github-backup#50]
The github-backup package cannot be importable because of how its named.  I think most of the code should be moved to the github_backup source code and the executable script file should be minimal.  This will help with #49 and for writing code that calls this as a library.

**Comment by josegonzalez** [comment]
Go for it. Honestly, I more or less merge anything that doesn't break functionality I use, so if you think this is a good move, thats fine by me.

**Comment by josegonzalez** [comment]
Doesn't seem like this is going to happen, but PRs welcome :)

**Comment by timm3** [comment]
I apologize for bumping a dead issue, but thought I could mention a workaround I put together until a PR gets made addressing this.

I used some `importlib` magic in my code to expose the github_backup library functions.
This has only been used in an Ubuntu 18.04 & lambda environment, and has not been tested with other operating systems or flavors.
This _exact_ code may not work, as I had to exclude most of the content, and only copied what I recall as being relevant.
**You should not use this in production. Just sayin'.**

```
import os
import sys

from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader

try:
    # "normal" pycharm development
    import github_backup
except ModuleNotFoundError:
    # docker/lambda development
    # `package` is in the path because that's what I named the directory for my lambda package...
    import package.github_backup as github_backup
init_path = github_backup.__file__
if "/lib" in init_path:
    init_ancestor = init_path.split('/lib', maxsplit=1)[0]
else:
    init_ancestor = init_path.split('/github_backup', maxsplit=1)[0]
desired_path = os.sep.join([init_ancestor, 'bin', 'github-backup'])
zspec = spec_from_loader("github_backup", SourceFileLoader("github_backup", desired_path))
zmodule = module_from_spec(zspec)
zspec.loader.exec_module(zmodule)
sys.modules["github_backup"] = zmodule
github_backup = zmodule
```

You can then pump arguments into sys.argv before calling github_backup.main(), though I did it before this oddball loading business.

**Comment by timm3** [comment]
@josegonzalez Is there a particular reason for structuring the module such that the actual code resides in `bin/github-backup` while the module's init file resides in `github_backup/__init__.py`?

What was the motivation for putting the code in the `bin` directory?

**Comment by josegonzalez** [comment]
None, other than it was a very small binary before and I didn't see a need to put it into the namespace.

**Comment by timm3** [comment]
@josegonzalez are there any functions you _wouldn't_ want exposed when the library gets imported?

**Comment by josegonzalez** [comment]
I don't really care to be honest. I've been merging almost every pull request, so go nuts.
