### ISSUE TITLE
failing on windows

### ISSUE THREAD

**Issue by nwsparks** [josegonzalez/python-github-backup#56]
python 3.6
git 2.11

Running the following command:

github-backup.py -t oauthtoken -o backupPath --all -P -O orguser

it runs, downloads a repo then terminates with the below errors. if i add --skip-existing it downloads the next repo but then terminates with the same message. same behavior if i change --all to --repositories.

> github-backup.py : Traceback (most recent call last):
> At line:1 char:1
> github-backup.py -t $OAuthToken -o $Backupfolder --repositories -P -O --skip-exi ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
>      FullyQualifiedErrorId : NativeCommandError
>  
>   File "C:\Program Files (x86)\Python36-32\Scripts\github-backup.py", line 815, in <module>
>     main()
>   File "C:\Program Files (x86)\Python36-32\Scripts\github-backup.py", line 810, in main
>     backup_repositories(args, output_directory, repositories)
>   File "C:\Program Files (x86)\Python36-32\Scripts\github-backup.py", line 518, in backup_repositories
>     bare_clone=args.bare_clone)
>   File "C:\Program Files (x86)\Python36-32\Scripts\github-backup.py", line 750, in fetch_repository
>     logging_subprocess(git_command, None)
>   File "C:\Program Files (x86)\Python36-32\Scripts\github-backup.py", line 89, in logging_subprocess
>     check_io()
>   File "C:\Program Files (x86)\Python36-32\Scripts\github-backup.py", line 79, in check_io
>     1000)[0]
> OSError: [WinError 10038] An operation was attempted on something that is not a socket

**Comment by josegonzalez** [comment]
I have never tested this on Windows - nor do I care to do so - but also I use Python 2.7. Maybe try that version of python?

**Comment by johnyf** [comment]
Please note that Python 2 is scheduled to expire: https://pythonclock.org. Using the `futurize` command from the `future` package (https://github.com/PythonCharmers/python-future) is a quick way to port to Python 3 automatically, and support Python 2 too.

**Comment by nwsparks** [comment]
ok no worries. was trying it there because i was hoping to call powershell to move the files to s3 after. same issue with 2.7. i'll see if i can mess around and get it done with python instead. thanks for the quick reply on it.

**Comment by josegonzalez** [comment]
@johnyf pull requests welcome.

**Comment by josegonzalez** [comment]
Closing. If someone wants to upgrade this to work on windows or python 3, thats cool and I'll merge it, but I'm certainly not going to do the work myself, as this works fine for me as is.
