### ISSUE TITLE
--incremental mode not working

### ISSUE THREAD

**Issue by hellyberry** [josegonzalez/python-github-backup#58]
Is the '--incremental' mode supposed to work? After performing a '--all'-backup, subsequent incremental backups do not work. Reproducibly with this error message. ([xxx] redacted by me)

Backing up user [xxx] to [xxx]
Retrieving repositories
Filtering repositories
Backing up repositories
Traceback (most recent call last):
  File "/usr/local/bin/github-backup", line 834, in <module>
    main()
  File "/usr/local/bin/github-backup", line 829, in main
    backup_repositories(args, output_directory, repositories)
  File "/usr/local/bin/github-backup", line 498, in backup_repositories
    last_update = max(repository['updated_at'] for repository in repositories)  # noqa
ValueError: max() arg is an empty sequence

I use Python 2.7.13.

**Comment by josegonzalez** [comment]
Seems like that `updated_at` wasn't there for one of your repositories.

Code for that is [here](https://github.com/josegonzalez/python-github-backup/blob/7a589f1e63e497ae536d10d5999996cfa9497c5d/bin/github-backup#L497), mind taking a look at the response of `/repos` to figure out what it should be?

**Comment by hellyberry** [comment]
Confirmed working. Thank you.
