### ISSUE TITLE
Is there a bare-bones working example somewhere?

### ISSUE THREAD

**Issue by afilbert** [josegonzalez/python-github-backup#63]
I've been poking around trying to get this to work and I keep getting the "too few arguments" error. Digging into the source code, now, but a plain ol' example would be nice addition to the readme. Thanks.

**Comment by josegonzalez** [comment]
I'd love a documentation pull request:

```
github-backup WhiteHouse \ # for the whitehouse github user
    --organization \ # which is a github organization, not a regular user
     --repositories # backup the repositories
    --output-directory /tmp/white-house \ # to a tmp folder (will be created if it doesn't exist)
    --token $ACCESS_TOKEN # with the specified access token
```

**Comment by mumblez** [comment]
always reports 'too few arguments', can you show a working example? (the above doesn't work)

**Comment by josegonzalez** [comment]
That example worked fine for me, and it seems that @afilbert confirmed it.

```
export ACCESS_TOKEN=SOME-GITHUB-TOKEN
github-backup WhiteHouse --token $ACCESS_TOKEN --organization --output-directory /tmp/white-house --repositories
Create output directory /private/tmp/white-house
Backing up user WhiteHouse to /private/tmp/white-house
Retrieving repositories
Filtering repositories
Backing up repositories
^C
```

Seems to work fine.

**Comment by mumblez** [comment]
thanks

**Comment by josegonzalez** [comment]
Would you be interested in making a PR to add that example to our documentation?

**Comment by mumblez** [comment]
https://github.com/josegonzalez/python-github-backup/pull/65
Hope this helps
