### ISSUE TITLE
Does this support LFS clones?

### ISSUE THREAD

**Issue by pieterclaerhout** [josegonzalez/python-github-backup#67]
We are using LFS (large-file support) in our repositories.

From our testing, we see that this is not supported by this script, correct?

If it's not supported, are you having any plans to add support for LFS clones?

**Comment by josegonzalez** [comment]
No its not. I don't have any plans to add it, as this project does everything I need.

If you'd like the functionality, you have two options:

- Contribute a pull request so I can review/merge.
- Pay me to build out the functionality for you.

**Comment by josegonzalez** [comment]
This is done by #68.
