### ISSUE TITLE
Restoring backups

### ISSUE THREAD

**Issue by vidavidorra** [josegonzalez/python-github-backup#71]
In issue #38 I read that this program doesn't include anything to restore the repository. Are any attempts made in creating such a script (by 3rd parties perhaps) or is it expected to be added to this program in the future?

**Comment by josegonzalez** [comment]
I don't expect this repo to ever have that functionality as it's called `python-github-backup`. You are welcome to work on a script that takes the output and puts it back onto a github user/organization though.

As far as I know, no one has done that. I have yet to need to restore, so I also have not done that.
