### ISSUE TITLE
How to prevent hitting API call rate limit

### ISSUE THREAD

**Issue by PaperFixie** [josegonzalez/python-github-backup#76]
My organization has a lot of GitHub data that we want to perform nightly backups of to a Drobo. I have been attempting to use this program to build it out, but I keep hitting the API rate limit, which times out the request for an increasing amount of time. Is there a way to tell the program to limit it's requests so that the data coming in is steady but not hitting the 5000 requests per minute threshold?

**Comment by josegonzalez** [comment]
There is not. Pull requests welcome.

**Comment by karlcow** [comment]
The API [rate limit](https://developer.github.com/v3/#rate-limiting) is 5000 HTTP requests per hour (not minutes as said above).

Let's say we want to backup issues.
A repo with more than 5000 issues, it starts to become a problem. 

The theoritical limit is 
* 1.38888 requests per second.

So we could artificially set a timer with one request per second and we would be safe. 
A backup for issues in a repo of 40,000+ issues would "only " take 11h6m40s.


https://github.com/josegonzalez/python-github-backup/blob/fac8e4274fdcee90ce52e42e70aa5639486a5013/bin/github-backup#L453-L454


https://github.com/josegonzalez/python-github-backup/blob/fac8e4274fdcee90ce52e42e70aa5639486a5013/bin/github-backup#L409-L451

There is also this piece of code which use rate limiting **but only** in case there's already an error. 
https://github.com/josegonzalez/python-github-backup/blob/fac8e4274fdcee90ce52e42e70aa5639486a5013/bin/github-backup#L505-L534

The strategy could be slightly different. 

* Counting the HTTP requests: 𝑛
* Marking the time of the first request: 𝑡₀ (seconds)
* time of the current request: 𝑡𝑐 (seconds)
* rate, an optional parameter: rate ≤ 1.38

```
if 𝑛 > (𝑡𝑐 - 𝑡₀) × rate : 
   wait 1 sec before next request
```

**Comment by eht16** [comment]
I've created a very simple throttling approach in #149.
This is not very clever and it simply pause API requests a fixed amount of seconds but it helps to stay within the rate limits.
My use case is: the GitHub API user used for the backup is also used elsewhere. It doesn't matter how long the backup takes as long as there are a few API requests left for the other uses.

**Comment by garymoon** [comment]
I am successfully using @eht16's throttling (💙) to keep below the rate limit when backing up very large orgs. I'm using `--throttle-limit 5000 --throttle-pause 0.6` but YMMV. IMO @eth16's work should close this issue 👍
