### ISSUE TITLE
Update clone if local repository already exists

### ISSUE THREAD

**Issue by anodium** [josegonzalez/python-github-backup#79]
Upon re-running the script on the same output directory, with these options `--all --all-starred --private --fork --bare --incremental`, I noticed that for repositories that already existed, `git` would return error 128.

I checked the error myself by running the same command in a separate terminal window, and noticed that `git` was failing to clone because "the destination path already exists and is not an empty directory".

Is there any way to have the script run `git remote update` for already existing repositories? Or, is there any way to force `git` into clobbering the directory (though this might be less efficient than pulling just the changes, since it would be cloning everything from scratch)?

**Comment by josegonzalez** [comment]
We definitely hande existing repositories correctly [here](https://github.com/josegonzalez/python-github-backup/blob/master/bin/github-backup#L778). Can you post logging output of your run?

**Comment by anodium** [comment]
Here's the output for one of my starred repos:
```
8<----- snip...
Cloning wii-u-gc-adapter repository from https://*****:x-oauth-basic@github.com/ToadKing/wii-u-gc-adapter.git to /run/media/andrea/5295089D57AEB47E/old_hdd/github/starred/ToadKing/wii-u-gc-adapter/repository
git returned 128:
	 git clone --mirror https://*****:x-oauth-basic@github.com/ToadKing/wii-u-gc-adapter.git /run/media/andrea/5295089D57AEB47E/old_hdd/github/starred/ToadKing/wii-u-gc-adapter/repository
Skipping wii-u-gc-adapter (https://*****:x-oauth-basic@github.com/ToadKing/wii-u-gc-adapter.wiki.git) since it's not initialized
Retrieving ToadKing/wii-u-gc-adapter issues
Saving 0 issues to disk
8<----- snip...
```

As you can see in line 5, it's stating that `git` returned a code of 128. On a seperate terminal, I ran the command in line 6 with my personal access token and `--verbose`, and it returned this:

```
andrea@inspiron ~>  git clone --verbose --mirror https://*****:x-oauth-basic@github.com/ToadKing/wii-u-gc-adapter.git /run/media/andrea/5295089D57AEB47E/old_hdd/github/starred/ToadKing/wii-u-gc-adapter/repository
fatal: destination path '/run/media/andrea/5295089D57AEB47E/old_hdd/github/starred/ToadKing/wii-u-gc-adapter/repository' already exists and is not an empty directory.
```

**Comment by josegonzalez** [comment]
Looks like the bare check failed. That code is [here](https://github.com/josegonzalez/python-github-backup/blob/master/bin/github-backup#L785)

What is the output of the following from within that directory?

```
git rev-parse  --is-bare-repository
```

**Comment by anodium** [comment]
```sh
andrea@inspiron ~> cd /run/media/andrea/5295089D57AEB47E/old_hdd/github/starred/ToadKing/wii-u-gc-adapter/repository
andrea@inspiron /r/m/a/5/o/g/s/T/w/repository> 
git rev-parse --is-bare-repository
true
```

**Comment by josegonzalez** [comment]
I wonder if it's getting newlines or something. I'll have to play around with this to add verbose logging for you to try later tonight.

**Comment by anodium** [comment]
Definitely would be willing to test out or help out any way I can, can't risk losing all my repositories.

**Comment by siepkes** [comment]
I'm encountering the exact same issue (also bare repos) on CentOS 7. GIT version is `2.9.3`.

**Comment by siepkes** [comment]
I've updated my GIT to version `2.16.2` to see if that would make a difference but that doesn't make a difference unfortunately.

**Comment by siepkes** [comment]
I no longer see this behavior (problem) with github-backup `0.20.0`.

**Comment by josegonzalez** [comment]
\o/

@anodium can you confirm it fixed it for you?

**Comment by anodium** [comment]
@josegonzalez Just confirmed, fixed and works properly now. Thank you very much! :+1:
