### ISSUE TITLE
Logging / verbose / tail

### ISSUE THREAD

**Issue by kMikaZu** [josegonzalez/python-github-backup#85]
Hi

Is there some way to export a log-file at the end of a backup-job? I would like to send a report to a Slack channel through a WebHook. 

Thanks

**Comment by josegonzalez** [comment]
Thats something I probably wouldn't build into this. You might look into wrapping this with a shell script that captures the output to a file via `tee`, then uploads that file to wherever you need it.

**Comment by josegonzalez** [comment]
Feel free to submit a pull request.
