### ISSUE TITLE
Wrong user's starred repositories downloaded

### ISSUE THREAD

**Issue by ethus3h** [josegonzalez/python-github-backup#87]
Hi! I didn't let it get very far before killing it, but when I ran the command like this:

`github-backup -u ethus3h -t [token] --all --repositories -P -F --gists --starred-gists --hooks --milestones --labels --bare --lfs --wikis --starred --all-starred --watched --followers --following --issues --issue-comments --issue-events --pulls --pull-comments --pull-commits --pull-details --hooks  SomeoneElsesUsername`

It started downloading all of my (ethus3h's) starred repositories, instead of the specified username's. I tried not including the `-u` and `-t` options, but it gave 401 Unauthorized.

This seems to prevent downloading the specified user's starred repositories.

It looks like this also affects starred gists.

**Comment by ethus3h** [comment]
Also, with this simpler command, no repositories at all were downloaded, despite them existing:

`github-backup -u ethus3h -t [token] --all --repositories -P -F --hooks --milestones --labels --bare --wikis --starred --watched --followers --following SomeoneElsesUsername`

**Comment by josegonzalez** [comment]
Can you show the output for both commands?

**Comment by ethus3h** [comment]
Ok, here are logs (don't worry, I revoked this access token already ;)

[2018june03-GitHubBackUpLog.txt](https://github.com/josegonzalez/python-github-backup/files/2066729/2018june03-GitHubBackUpLog.txt)

Thanks!

(P.S. looks like there was another random type mismatch issue, the real issue is that the repo it was downloading — vog/bscp — is one of my stars, not one of the downloaded user's)

**Comment by whwright** [comment]
Hello! I think this is my fault using `/user/starred` instead of `/user/{username}/starred` from https://github.com/josegonzalez/python-github-backup/pull/78.

I'll put a fix up!

**Comment by ethus3h** [comment]
Thank you for the fix! I have tested it and it works :D (aside from #93, but that's got its own issue now).

(It's still crashing after a bit — "list indices must be integers, not str", but that's something else.)
