### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by uzerus** [josegonzalez/python-github-backup#89]
After installing github-backup via pip install **github-backup** or _this git clone_ ...
`bash: /usr/bin/github-backup: No such file or directory`

Distribution: Ubuntu 16.04

Maybe it;s cos before i installed another tool named github-backup but a little older

Fixed by 
`cp /usr/local/bin/github-backup /usr/bin/github-backup`

**Comment by josegonzalez** [comment]
Seems like a bug on your system, but glad you got a fix.
