### ISSUE TITLE
--all option does not include everything

### ISSUE THREAD

**Issue by tobozo** [josegonzalez/python-github-backup#90]
Thanks for the tool it's excellent 👍 

![image](https://user-images.githubusercontent.com/1893754/43702588-83663350-995a-11e8-91df-58be6ea6352f.png)

Just got confused by the description of `--all` and the meaning of "everything" that seem to be very user-centric as I had to add flags to get the forked and watched repos.

Other than that all went well and worked like a charm.
Thanks again for the good work!

**Comment by ecki** [comment]
I would agree, the help should mark all options which are not included in all. I was actually concerend --all would include too much (like the starred repos). So the choice of all seems reasonable, just that it should better document it.

**Comment by tobozo** [comment]
thanks, and happy holidays ^_^

**Comment by ecki** [comment]
Sorry its https://github.com/josegonzalez/python-github-backup/pull/101
