### ISSUE TITLE
How do we restore a repo/organization?

### ISSUE THREAD

**Issue by BarbzYHOOL** [josegonzalez/python-github-backup#96]
Is there a way to restore a repo or all repos with issues, PRs etc?

either to github or gitlab or somewhere else

**Comment by josegonzalez** [comment]
This repository does not do restores, it is purely for backup purposes. If you wish to have a restore script, feel free to write one.

**Comment by BarbzYHOOL** [comment]
Ok thank you but I wonder if it's even possible ^^

**Comment by josegonzalez** [comment]
I don't know, but since its not something I'm interested in, I won't look into the answer.

On the off-chance I _do_ need to restore from the backup I generate, I'll write a script then to parse my files and write the correct entries.
